### ISSUE TITLE
Integrate Cobertura for code coverage

### ISSUE THREAD

**Issue by abhishekdas99** [qubole/rubix#100]

**Comment by vrajat** [comment]
Can you also quickly evaluate https://coveralls.io/ ?

**Comment by jordanw-bq** [comment]
Coveralls looks fairly easy to set-up, similar to Travis CI. I'll include integrating this as part of the task.

**Comment by vrajat** [comment]
One of them is sufficient. If coveralls is easy, let's do that one alone
and evaluate.

**Comment by jordanw-bq** [comment]
Coveralls depends on code coverage reports generated by tools like Cobertura. It seems Coveralls acts more as an analysis tool for the reports, which integrates well with our current setup (GitHub Travis CI) and will likely be useful for us going forward.

**Comment by vrajat** [comment]
Got it. Thanks for the clarification.
