### ISSUE TITLE
Move from 4-space to 2-space indents

### ISSUE THREAD

**Issue by jordanw-bq** [qubole/rubix#105]
Most open-source project use 2-space indents for their source files. We want to use this for RubiX as well.

**Comment by jordanw-bq** [comment]
This will include updating our Checkstyle checks.xml to enforce indenting.

**Comment by abhishekdas99** [comment]
As part of this we are going to update the checkstyle and fix all the errors coming because of the change

**Comment by abhishekdas99** [comment]
https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml

**Comment by jordanw-bq** [comment]
@abhishekdas99 To confirm, will we be completely switching to Google's checks?

**Comment by abhishekdas99** [comment]
@stagraqubole was referring to airlift (facebook) code style. We can pick either of them. My preference is to have 2-space indents rather than 4 space indents.
