### ISSUE TITLE
Rubix + Hive usage instructions

### ISSUE THREAD

**Issue by vrajat** [qubole/rubix#126]
Current readme has the following text:

> Add RubiX jars: rubix-bookkeeper.jar, rubix-core.jar, rubix-hadoop1 either to hadoop/lib directly or via add jar command.
All these jars are packaged in rubix-hadoop1.tar under assembly module
Configuration changes: Use following configs to start using RubiX
fs.s3n.impl=com.qubole.rubix.hadoop1.CachingNativeS3FileSystem
fs.s3.impl=com.qubole.rubix.hadoop1.CachingNativeS3FileSystem

We should also consider coding this up in rubix-admin.

**Comment by abhishekdas99** [comment]
Add RubiX jars: 
rubix-bookkeeper.jar, rubix-core.jar, rubix-hadoop2 either to hadoop/lib directly or via add jar command.

Configuration changes: Set the following configurations when starting hive client
fs.s3n.impl=com.qubole.rubix.hadoop2.CachingNativeS3FileSystem
fs.s3.impl=com.qubole.rubix.hadoop2.CachingNativeS3FileSystem
fs.s3a.impl=com.qubole.rubix.hadoop2.CachingS3AFileSystem
