### ISSUE TITLE
Update copyright for source files

### ISSUE THREAD

**Issue by jordanw-bq** [qubole/rubix#137]
The copyright in all source files is still 2016. These should be updated to 2018 to match the current year.

Additionally, strategies for keeping copyrights up-to-date should be investigated.

**Comment by vrajat** [comment]
I found this link that *I think* suggests that we can ignore updating the year. I am no lawyer though :)

https://softwareengineering.stackexchange.com/questions/130478/what-copyright-date-for-an-update-to-an-open-source-project-from-last-year
