### ISSUE TITLE
how to use rubix in spark, jvm apps etc.

### ISSUE THREAD

**Issue by manishmalhotrawork** [qubole/rubix#240]
example code, or test-cases documentation etc.
difficult to adapt and test it, because of this.

**Comment by abhishekdas99** [comment]
You can use RubiX for your spark applications by configuring the filesystems properly.
The configs need to be set:

spark.hadoop.fs.s3.impl         com.qubole.rubix.hadoop2.CachingS3AFileSystem
spark.hadoop.fs.s3n.impl        com.qubole.rubix.hadoop2.CachingS3AFileSystem
spark.hadoop.fs.s3a.impl        com.qubole.rubix.hadoop2.CachingS3AFileSystem

or 

spark.hadoop.fs.s3.impl         com.qubole.rubix.hadoop2.CachingS3AFileSystem
spark.hadoop.fs.s3n.impl        com.qubole.rubix.hadoop2.CachingS3AFileSystem
spark.hadoop.fs.s3a.impl        com.qubole.rubix.hadoop2.CachingS3AFileSystem
