### ISSUE TITLE
Master Bookkeeper is getting overloaded with connection refused errors

### ISSUE THREAD

**Issue by kvankayala** [qubole/rubix#341]
We see lot of connection refused errors 

In large clusters, the spark performance is getting degraded when the driver gets launched in worker nodes.

**Comment by stagraqubole** [comment]
@kvankayala can you also share stack traces to point out the endpoints that usually see this

**Comment by kvankayala** [comment]
I see a lot of following errors:

> App > 20/02/05 22:44:52 pool-34-thread-5 ERROR CachingFileSystem: Error while getting Node HostName. Fallingback on RemoteFileSystem. org.apache.thrift.shaded.transport.TTransportException: java.net.ConnectException: Cannot assign requested address (connect failed)

App > 20/02/05 22:56:42 pool-35-thread-3 ERROR CachingFileSystem: Error while getting Node HostName. Fallingback on RemoteFileSystem. org.apache.thrift.shaded.transport.TTransportException: java.net.SocketTimeoutException: Read timed out

App > 20/02/05 23:08:37 pool-38-thread-2 ERROR CachingFileSystem: Error while getting Node HostName. Falling back on RemoteFileSystem. org.apache.thrift.shaded.transport.TTransportException: java.net.SocketTimeoutException: connect timed out
We don't have the stack trace. Because we tackle the exception by reading the file information directly from s3. (in **getFileBlockLocations** method in **CachingFileSystem** class)

In Spark, we wants the list of the files and their size to compute RDD partitions. 
App > 20/02/05 22:55:11 main INFO SparkFileStatusCache: prepared cache with 1824 dirs and 364800 files
App > 20/02/05 22:55:26 main INFO InputPathProcessor: Using 8 threads for listLocatedStatus

This is happening before the tasks are allocated to the executors i.e., before DAGScheduler.

Using sparklens, I could observe that the driver is consuming lot of time than expected.

**Comment by stagraqubole** [comment]
The part of code that caused this regression was reverted
