### ISSUE TITLE
Lower log level of cache eviction to debug

### ISSUE THREAD

**Issue by JamesRTaylor** [qubole/rubix#445]
We're seeing a ton of these warning level messages about cache evictions:
`2020-08-25T20:27:44.97592 2020-08-25T20:27:44.975Z   WARN  RemoteFetchProcessor RUNNING  com.qubole.rubix.bookkeeper.FileMetadata    Evicting s3a://lyft-compactevents-production/c/event_name=my_event/sparkbd30196a182a43439d94188472c442f5/ds=2020-08-16/hr=16/part-00012-a6097de2-7fae-4386-af45-8f014310c9dd.c000.snappy.parquet due to SIZE`

Would it be possible to lower the log level to debug?

**Comment by JamesRTaylor** [comment]
Would it be possible to do this one before next release, @harmandeeps?

**Comment by harmandeeps** [comment]
@JamesRTaylor : yes, will fix this issue before next release. 

Thanks!

**Comment by harmandeeps** [comment]
@JamesRTaylor : fixed, Thanks.

**Comment by JamesRTaylor** [comment]
Thank you, @harmandeeps!
