### ISSUE TITLE
Available cache space is computed before cache directories are cleaned up during startup

### ISSUE THREAD

**Issue by sopel39** [qubole/rubix#454]
See `BookKeeper#BookKeeper(org.apache.hadoop.conf.Configuration, com.qubole.rubix.common.metrics.BookKeeperMetrics, com.google.common.base.Ticker)`.
Inside there is,
```
    initializeCache(conf, ticker);
    cleanupOldCacheFiles(conf);
```
However, `initializeCache` uses `java.io.File#getUsableSpace` to compute cache size. Therefore when node is restarted with let's say 80% cache partition occupied before, Rubix will use at most only 20% of remaining space.

Should these method calls be revered?

**Comment by stagraqubole** [comment]
Yes, this needs to be fixed.

**Comment by harmandeeps** [comment]
Fixed in #455. Closing this issue. 
Thanks!

**Comment by sopel39** [comment]
Will you create PR to PrestoSQL once Rubix is released?

**Comment by harmandeeps** [comment]
@sopel39 : yeah, I will create the PR.
