### ISSUE TITLE
Read - Write - Read inconsistency in Spark

### ISSUE THREAD

**Issue by arajagopal17** [qubole/rubix#61]
> When writing to a file in cache, the application which wrote the data is able to pick up the change but a different spark application running on the same cluster is not able to. 
> It continues to serve stale data till the application is restarted or a write takes place. In such a scenario, all the updates are present including the most recent write.

**Comment by stagraqubole** [comment]
Were you able to root cause this? One thing that we discussed was that unless a new InputStream is opened by client, it will keep reading old data. Is that what is happening in Spark?

**Comment by arajagopal17** [comment]
I checked the inputstream, Spark does close the inputstream in each worker once the task is completed. So a new inputstream is opened for each read. 
Also, I had earlier said the cache invalidation in the overwrite case doesn't work. That is incorrect, overwrite seems to be invalidating the cache properly. The problem lies in the insert operation which creates a new set of files on the s3 side. I am checking if the listStatus call is reflecting the changes correctly after a write.

**Comment by arajagopal17** [comment]
This seems to be due to metadata caching on the spark side. This can be resolved by setting the metadata config flag to false (spark.sql.parquet.cacheMetadata) or by running the refresh table command. I am closing this issue.
